[project]
name = "lmnop-handler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Scott Hyndman", email = "scotty.hyndman@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastmcp>=3.2.4",
    "pydantic>=2.13.3",
]

[project.scripts]
lmnop-handler = "lmnop.handler:main"

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "lmnop"
namespace = true

[tool.basedpyright]
include = ["src", "tests"]
exclude = [
  "**/__pycache__",
]
defineConstant = { DEBUG = true }

reportMissingImports = "error"
reportMissingTypeStubs = false

pythonVersion = "3.14"
pythonPlatform = "Linux"

[dependency-groups]
dev = [
    "basedpyright>=1.39.3",
    "pytest>=9.0.3",
]
