#!/usr/bin/with-contenv bash

if [[ ! -f /config/.config/openbox/menu.xml ]]; then
    mkdir -p /config/.config/openbox
    cp /defaults/menu.xml /config/.config/openbox/menu.xml
    chown -R abc:abc /config/.config
fi
